PWGHF: add xic+ in ini file and rename
AliceO2Group/O2DPG pull request #1582
Opened 2024-04-08 10:21 UTC by ZFederica

- add xic+ to vector of trigger hadrons in .ini file
- rename the .ini file GeneratorHF_D2H_ccbar_and_bbbar_gap5_Mode2_XiC_OmegaC.ini --> GeneratorHF_D2H_ccbar_and_bbbar_gap5_Mode2_CharmBaryons
(cgf file pythia8_charmhadronic_with_decays_Mode2.cfg already includes the xic+ decays)
The .ini file modified is the same as the one used in the test prductions with gap 5

@cterrevo @fcatalan92

2024-04-08 13:41 UTC, fgrosa commented
Hi @ZFederica, probably you have a typo in the `.ini` file name that is named `GeneratorHF_D2H_ccbar_and_bbbar_gap5_Mode2_CharmBaryons copy.ini`, could you please fix it? Thanks!

2024-04-08 13:45 UTC, fgrosa requested changes
Hi @ZFederica, probably you have a typo in the `.ini` file name that is named `GeneratorHF_D2H_ccbar_and_bbbar_gap5_Mode2_CharmBaryons copy.ini`, could you please fix it? Thanks!

2024-04-09 08:28 UTC, fcatalan92 approved these changes

2024-04-09 08:42 UTC, fgrosa approved these changes

2024-04-09 08:42 UTC, merged