interpolation w-flow uses ITS-TPC as map-extraction src, all for track-src
AliceO2Group/O2DPG pull request #1644
Opened 2024-05-22 13:08 UTC by shahor02

2024-05-22 16:06 UTC, martenole approved these changes

2024-05-22 18:16 UTC, wiechula requested changes

2024-05-22 18:16 UTC, wiechula commented on DATA/production/configurations/asyncReco/setenv_extra.sh
>      export CONFIG_EXTRA_PROCESS_o2_tpc_scdcalib_interpolation_workflow="scdcalib.maxTracksPerCalibSlot=35000000;scdcalib.minPtNoOuterPoint=0.2;scdcalib.maxQ2Pt=5;scdcalib.minITSNClsNoOuterPoint=6;scd
I propose to also adjust this slightly
```suggestion
    export CONFIG_EXTRA_PROCESS_o2_tpc_scdcalib_interpolation_workflow="scdcalib.additionalTracksMap=35000000;scdcalib.minPtNoOuterPoint=0.2;scdcalib.maxQ2Pt=5;scdcalib.minITSNClsNoOuterPoint=6;scdcalib.minITSNCls=4;scdcalib.minTPCNClsNoOuterPoint=90;scdcalib.minTOFTRDPVContributors=2"
```

2024-05-22 18:22 UTC, shahor02 commented
thanks @wiechula

2024-05-22 18:35 UTC, wiechula approved these changes

2024-05-22 21:45 UTC, merged

2024-08-07 10:31 UTC, alcaliva commented
Dear @wiechula, note that we had to add this PR in the labels "async-2024-pp-apass1" and "async-2024-pp-cpass0" in order to apply the PR https://github.com/AliceO2Group/O2DPG/pull/1698 which is needed for the labels above