Add Skimming for TPC to analysis QC
AliceO2Group/O2DPG pull request #967
Opened 2023-03-23 13:21 UTC by njacazio

2023-03-23 13:22 UTC, njacazio commented
@noferini @jezwilkinson this is my suggestion

2023-03-23 13:47 UTC, jezwilkinson commented
Hi @njacazio - thanks very much, this looks good.
Just one question, does the configuration JSON become hardcoded here or can it be customised? We may need to still tweak the downsampling factors depending on the size of the datasets

2023-03-23 13:50 UTC, njacazio commented
Hi @jezwilkinson the JSON is hardcoded, one thing could be to have the downsampling fetched via CCDB so that it automagically matches the correct data. But this requires some dev.
I let @benedikt-voelkel comment on the best approach

2023-03-23 14:57 UTC, benedikt-voelkel commented
Hej @njacazio 
Do you have an estimation how long this task takes on - say - 1,000 pp events? Just so that we keep track of what we have compared to MC or reco.

2023-03-23 14:59 UTC, benedikt-voelkel requested changes

2023-03-23 14:59 UTC, benedikt-voelkel commented on MC/config/analysis_testing/json/analyses_config.json
> +            "data": "json://${O2DPG_ROOT}/MC/config/analysis_testing/json/analysis-skimming.json",
I suggest to rename to `analysis-testing-TPCSkimming.json` to align with the other configs we have

2023-03-23 17:13 UTC, jezwilkinson commented
> Do you have an estimation how long this task takes on - say - 1,000 pp events? Just so that we keep track of what we have compared to MC or reco.

@benedikt-voelkel  I don't have a concrete estimate for time/1k events, but the running statistics can be found in the previous Hyperloop runs for the wagon (e.g. https://alimonitor.cern.ch/hyperloop/train-run/70232, https://alimonitor.cern.ch/hyperloop/train-run/70257) if that helps

2023-03-23 17:29 UTC, benedikt-voelkel commented
Thanks!
ok, let's do it line this:
@njacazio could you set the `enabled` flag in the configuration to `false` for now?
Then - as soon as you have tested that it works in principle - we can merge this PR.
After that, I will test it on some of our nightlies to have an idea what the timing is roughly.

2023-03-23 17:58 UTC, njacazio commented
Hi @benedikt-voelkel done!

2023-03-23 19:00 UTC, benedikt-voelkel approved these changes

2023-03-24 08:31 UTC, merged

2023-03-24 11:28 UTC, njacazio commented
Hi @benedikt-voelkel thanks a lot for the prompt action! Then we wait for you and the alibi test before going forward